-- MySQL Script generated by MySQL Workbench
-- Mon Oct 13 10:23:14 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id_funcionario` INT NOT NULL,
  `nome_funcionario` VARCHAR(100) NOT NULL,
  `telefone_funcionario` VARCHAR(20) NULL,
  `email_funcionario` VARCHAR(100) NULL,
  PRIMARY KEY (`id_funcionario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome_cliente` VARCHAR(100) NOT NULL,
  `cpf_cliente` CHAR(11) NULL,
  `email_cliente` VARCHAR(100) NULL,
  `telefone_cliente` VARCHAR(20) NULL,
  `endereco_cliente` VARCHAR(100) NULL,
  `dt_nasc_cliente` DATE NULL,
  `venda_modelo_marca_id_marca` INT NOT NULL,
  PRIMARY KEY (`id_cliente`, `venda_modelo_marca_id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `id_marca` INT NOT NULL,
  `nome_marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`modelo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`modelo` (
  `id_modelo` INT NOT NULL,
  `nome_modelo` VARCHAR(45) NOT NULL,
  `cor_modelo` VARCHAR(20) NULL,
  `ano_modelo` YEAR NULL,
  `tipo_modelo` VARCHAR(45) NULL,
  `marca_id_marca` INT NOT NULL,
  PRIMARY KEY (`id_modelo`, `marca_id_marca`),
  INDEX `fk_modelo_marca_idx` (`marca_id_marca` ASC) VISIBLE,
  CONSTRAINT `fk_modelo_marca`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `mydb`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`venda` (
  `id_venda` INT NOT NULL,
  `data_venda` VARCHAR(45) NULL,
  `valor_venda` DECIMAL(10,2) NULL,
  `modelo_id_modelo` INT NOT NULL,
  `funcionario_id_funcionario` INT NOT NULL,
  `modelo_id_modelo1` INT NOT NULL,
  `modelo_marca_id_marca` INT NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `cliente_venda_modelo_marca_id_marca` INT NOT NULL,
  `funcionario_id_funcionario1` INT NOT NULL,
  PRIMARY KEY (`id_venda`, `modelo_id_modelo`, `funcionario_id_funcionario`, `modelo_id_modelo1`, `modelo_marca_id_marca`, `cliente_id_cliente`, `cliente_venda_modelo_marca_id_marca`, `funcionario_id_funcionario1`),
  INDEX `fk_venda_modelo1_idx` (`modelo_id_modelo1` ASC, `modelo_marca_id_marca` ASC) VISIBLE,
  INDEX `fk_venda_cliente1_idx` (`cliente_id_cliente` ASC, `cliente_venda_modelo_marca_id_marca` ASC) VISIBLE,
  INDEX `fk_venda_funcionario1_idx` (`funcionario_id_funcionario1` ASC) VISIBLE,
  CONSTRAINT `fk_venda_modelo1`
    FOREIGN KEY (`modelo_id_modelo1` , `modelo_marca_id_marca`)
    REFERENCES `mydb`.`modelo` (`id_modelo` , `marca_id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_cliente1`
    FOREIGN KEY (`cliente_id_cliente` , `cliente_venda_modelo_marca_id_marca`)
    REFERENCES `mydb`.`cliente` (`id_cliente` , `venda_modelo_marca_id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_funcionario1`
    FOREIGN KEY (`funcionario_id_funcionario1`)
    REFERENCES `mydb`.`funcionario` (`id_funcionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
